# Generated by Django 3.1.6 on 2021-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfessionOption',
            new_name='Profession',
        ),
        migrations.AlterModelOptions(
            name='checkoutoptions',
            options={'verbose_name': 'Checkout Option'},
        ),
        migrations.AlterModelOptions(
            name='contactoptions',
            options={'verbose_name': 'Contact Option'},
        ),
        migrations.AlterModelOptions(
            name='pageoptions',
            options={'verbose_name': 'Page Option'},
        ),
        migrations.AlterField(
            model_name='checkoutoptions',
            name='image',
            field=models.CharField(max_length=30),
        ),
    ]
