# Generated by Django 3.1.6 on 2021-02-09 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_auto_20210209_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageoptions",
            name="custom_portfolio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="checkout.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="pageoptions",
            name="custom_reviews",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="checkout.review",
            ),
        ),
    ]
