# Generated by Django 3.1.6 on 2021-02-13 14:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210209_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='pageoptions',
            name='custom_portfolio',
        ),
        migrations.RemoveField(
            model_name='pageoptions',
            name='custom_reviews',
        ),
        migrations.RemoveField(
            model_name='pageoptions',
            name='professions',
        ),
        migrations.RemoveField(
            model_name='checkoutoptions',
            name='contact_options',
        ),
        migrations.RemoveField(
            model_name='checkoutoptions',
            name='page_options',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='quote',
        ),
        migrations.AddField(
            model_name='checkoutoptions',
            name='custom_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.portfolio'),
        ),
        migrations.AddField(
            model_name='checkoutoptions',
            name='messenger',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='checkoutoptions',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='checkoutoptions',
            name='professions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AddField(
            model_name='checkoutoptions',
            name='reviewers_image',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutoptions',
            name='reviewers_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutoptions',
            name='reviewers_quote',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutoptions',
            name='whatsapp',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContactOptions',
        ),
        migrations.DeleteModel(
            name='PageOptions',
        ),
    ]
