# Generated by Django 3.1.6 on 2021-02-14 13:36

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_stage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('whatsapp', models.BooleanField()),
                ('messenger', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Contact Option',
            },
        ),
        migrations.CreateModel(
            name='PageOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None)),
                ('profile_image', models.CharField(max_length=30)),
                ('review_name', models.CharField(max_length=30)),
                ('review_image', models.CharField(max_length=30)),
                ('review_quote', models.CharField(max_length=30)),
                ('portfolio_image', models.CharField(max_length=30)),
                ('portfolio_description', models.CharField(max_length=900)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkoutoptions',
            name='custom_portfolio',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='CheckoutOptions',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
