# Generated by Django 3.1.6 on 2021-02-06 11:13

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("whatsapp", models.BooleanField()),
                ("messenger", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=30)),
                ("alt", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("image", models.CharField(max_length=30)),
                ("quote", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "image_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.image",
                    ),
                ),
            ],
            bases=("form.image",),
        ),
        migrations.CreateModel(
            name="PageOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_reviews",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.review"
                    ),
                ),
                (
                    "professions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.professionoptions",
                    ),
                ),
                (
                    "custom_portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.portfolio"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "contact_options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.contactoptions",
                    ),
                ),
                (
                    "page_options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.pageoptions",
                    ),
                ),
            ],
        ),
    ]
