# Generated by Django 3.1.6 on 2021-02-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactOptions",
            new_name="ContactOption",
        ),
        migrations.RenameModel(
            old_name="FormOptions",
            new_name="FormOption",
        ),
        migrations.RenameModel(
            old_name="PageOptions",
            new_name="PageOption",
        ),
        migrations.RenameModel(
            old_name="ProfessionOptions",
            new_name="ProfessionOption",
        ),
    ]
