name: sol
on: [push]
env:
  production: True
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.9]
        node-version: [14]

    steps:
      - name: Set up Python ${{ matrix.python-version }}}
        uses: actions/checkout@v2

      - name: Set up poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install dependencies
        run: poetry install

      - name: Format with black
        run: poetry run black

      - name: Format with isort
        run: poetry run isort .

      - name: Lint with flake8
        run: poetry run flake8

      - name: Test with pytest
        run: poetry run pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup & Build Tailwind
        working-directory: src/apps/theme/js
        run: |
          npm i
          npm run build

      - name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: '95.179.202.170'
            app-name: 'handyman'